fetch: #namespace

    #qlearn parameters
    task_and_robot_environment_name: 'FetchSimpleTest-v0'
    ros_ws_abspath: "/home/noio0925/catkin_ws"
    n_actions: 6 # X+/-,Y+/-,Z+/-
    n_observations: 3 # XYZ of the TCP and the distance from GOAL
    episodes_training: 40
    episodes_running: 10
    max_iterations: 10
    n_win_ticks: 50 # If the mean of rewards is bigger than this and have passed min_episodes, the task is considered finished
    min_episodes: 10
    alpha: 0.01 # Learning Rate
    alpha_decay: 0.01
    gamma: 1.0 # future rewards value 0 none 1 a lot
    epsilon: 1.0 # exploration, 0 none 1 a lot
    epsilon_decay: 0.995 # how we reduse the exploration
    epsilon_min: 0.01 # minimum value that epsilon can have
    batch_size: 64 # maximum size of the batches sampled from memory


    monitor: True
    quiet: False


